# --------------------------------------------------------------------------------------------------------------------- #
# WRF experiments
# --------------------------------------------------------------------------------------------------------------------- #

save_loc: '/glade/work/ksha/DWC_runs/FE_09/'
seed: 1000

data:
    levels: 9

    domain_random_subset:
      activate: True
      size_list_train: [[256, 256], [256, 256]]
      size_list_valid: [[256, 256]]
      size_full: [592, 592]
      
    variables: ['u', 'v', 'w', 'theta', 'rho', 'qv', 'TKE_0']
    save_loc: '/glade/derecho/scratch/ksha/FastEddy/FE_09lev/experiment_*.zarr'

    static_variables: ['BuildingHeights_norm', 'BuildingMask_norm', 'LandCover_norm', 'topoPos_norm', 'topoWRF_norm']
    save_loc_static: '/glade/derecho/scratch/ksha/FastEddy/static/FE_static_short.zarr'

    history_len: 1
    valid_history_len: 1

    forecast_len: 0
    valid_forecast_len: 0

    # mean / std path
    mean_path: '/glade/derecho/scratch/ksha/FastEddy/mean_std/FE_mean_09lev.nc'
    std_path: '/glade/derecho/scratch/ksha/FastEddy/mean_std/FE_std_residual_09lev.nc'

    # train / validation split
    train_years: [0, 10]
    valid_years: [10, 11]
    test_years: [11, 13]

    # data workflow
    scaler_type: 'std-les'

    one_shot: False
    lead_time_periods: 1
    skip_periods: null
    static_first: True


trainer:
    type: standard-les
    
    mode: fsdp
    cpu_offload: False
    activation_checkpoint: True
    
    load_weights: False
    load_optimizer: False
    load_scaler: False
    load_sheduler: False
    num_epoch: 8
    
    skip_validation: False
    update_learning_rate: False
    
    save_backup_weights: True
    save_best_weights: True
    save_metric_vars: True
    
    learning_rate: 1.0e-03
    weight_decay: 1.0e-06
    
    train_batch_size: 1
    valid_batch_size: 1
    
    batches_per_epoch: 1500
    valid_batches_per_epoch: 20
    stopping_patience: 999
    
    start_epoch: 0
    
    reload_epoch: True
    epochs: &epochs 120
    
    use_scheduler: True
    scheduler: {'scheduler_type': 'cosine-annealing', 'T_max': *epochs,  'last_epoch': -1}
    
    amp: False
    grad_accum_every: 1 
    grad_max_norm: 32.0
    thread_workers: 4
    valid_thread_workers: 0


model:
    type: "fuxi"

    frames: 1                # number of input states
    image_height: 256        # number of latitude grids
    image_width: 256         # number of longitude grids
    levels: 9                # number of upper-air variable levels
    channels: 7              # upper-air variable channels
    surface_channels: 0      # surface variable channels
    input_only_channels: 5   # dynamic forcing, forcing, static channels
    output_only_channels: 0  # diagnostic variable channels

    # patchify layer
    patch_height: 2         # number of latitude grids in each 3D patch
    patch_width: 2          # number of longitude grids in each 3D patch
    frame_patch_size: 1     # number of input states in each 3D patch

    # hidden layers
    dim: 1280               # dimension (default: 1536)
    num_groups: 32          # number of groups (default: 32)
    num_heads: 8            # number of heads (default: 8)
    window_size: 7          # window size (default: 7)
    depth: 36               # number of swin transformers (default: 48)

    # use spectral norm
    # drop_path: 0.2
    use_spectral_norm: True

    # use interpolation to match the output size
    interp: False

    padding_conf:
        activate: False

    post_conf:
        activate: True

        tracer_fixer:
            activate: True
            denorm: True
            tracer_name: ['rho', 'qv']
            tracer_thres: [0, 0]

    
loss: 
    # the main training loss
    training_loss: "mse"
   
    use_power_loss: False
    use_spectral_loss: False

    use_latitude_weights: False
    latitude_weights: '/glade/derecho/scratch/ksha/FastEddy/static/FE_static_short.zarr'

    use_variable_weights: True
    variable_weights:
        u: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        v: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        w: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        rho: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        qv: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        theta: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]
        TKE_0: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2]

